/**
 * Design reminder — مسار مادة وبناء: صفحات المحتوى تعطي النصوص الأصلية والوسائط وزنًا تحريريًا ومسارات قراءة واضحة مع سطح داكن/عاجي متبادل.
 */
import { useState, type FormEvent } from "react";
import { ArrowUpLeft, CalendarDays, CheckCircle2, Clock3, FileText, Mail, MapPin, MessageCircle, Phone, Send, UserRound } from "lucide-react";
import { Link } from "wouter";
import { SignalMatrix } from "@/components/SignalMatrix";
import { SiteShell } from "@/components/SiteShell";
import { bio, blog, contact, projects, services } from "@/data/portfolio";

function PageIntro({ index, label, title, copy }: { index: string; label: string; title: string; copy: string }) { return <section className="page-intro"><p className="eyebrow"><SignalMatrix label={index} /><span>{label}</span></p><h1>{title}</h1><p>{copy}</p></section>; }

export function AboutPage() { return <SiteShell><PageIntro index="02" label="PROFILE" title="من أنا (عني)" copy={bio} /><section className="section paper-section about-layout"><img src={contact.aboutImage} alt="المهندس Fahmi Ali" /><div className="about-copy"><p className="eyebrow dark"><SignalMatrix label="A" /><span>ARCHITECT / TAIZ</span></p><h2>تصميم يُترجم الاحتياج إلى <em>مسار قابل للبناء.</em></h2><p>{bio}</p><a className="text-link" href={contact.cv} target="_blank" rel="noreferrer">عرض السيرة الذاتية <ArrowUpLeft /></a></div></section></SiteShell>; }

export function ServicesPage() { return <SiteShell><PageIntro index="03" label="SERVICES" title="خدماتي" copy="أقدم مجموعة متكاملة من الخدمات الهندسية" /><section className="section services-section"><div className="services-list">{services.map(service => <article key={service.number} className="service-row"><span className="service-number">{service.number}</span><div><p className="service-tag">{service.tag}</p><h2>{service.title}</h2><p>{service.description}</p></div><strong>{service.price}</strong></article>)}</div></section></SiteShell>; }

export function BlogsPage() { return <SiteShell><PageIntro index="05" label="المدونة" title="مدونتي" copy="أفكاري، خبراتي، ورحلتي في عالم الهندسة والإبداع" /><section className="blog-stats"><span><b>1</b> مقالة منشورة</span><span><b>89</b> مشاهدة إجمالية</span><span><b>05 / 2025</b> سنة النشاط</span></section><section className="section paper-section"><article className="blog-card"><img src={blog.image} alt={blog.title} /><div><p className="eyebrow dark"><SignalMatrix label="01" /><span>مقال</span></p><h2>{blog.title}</h2><p>{blog.excerpt}</p><div className="article-data"><span><CalendarDays /> {blog.date}</span><span><Clock3 /> {blog.readTime}</span></div><Link href="/blogs/5" className="button button-ink">اقرأ المقال <ArrowUpLeft /></Link></div></article></section></SiteShell>; }

export function BlogDetailPage() { return <SiteShell><article className="article-page"><div className="article-crumb"><Link href="/">الرئيسية</Link><span>/</span><Link href="/blogs">المقالات</Link></div><p className="eyebrow"><SignalMatrix label="05" /><span>مقال / 01</span></p><h1>{blog.title}</h1><div className="article-author"><img src={contact.profileImage} alt="Fahmi Ali" /><span>كاتب المقال: <b>Fahmi Ali</b></span><span>{blog.date}</span><span>{blog.views}</span><span>{blog.readTime}</span></div><img className="article-cover" src={blog.image} alt={blog.title} /><div className="article-body">{blog.body.map((line, index) => <p key={index}>{line}</p>)}</div><div className="article-tag">{blog.tag}</div><div className="article-author-box"><UserRound /><div><p>عن الكاتب</p><h2>مهندس معماري متخصص</h2><p>{bio}</p></div></div></article></SiteShell>; }

export function CertificatesPage() { return <SiteShell><PageIntro index="06" label="CREDENTIALS" title="الشهادات الأكاديمية" copy="شهاداتي العلمية والدورات التدريبية" /><section className="empty-section"><FileText /><h2>سجل الشهادات قيد الإضافة.</h2><p>لا توجد شهادات أو دورات ظاهرة في المصدر الحالي، لذلك لم تتم إضافة محتوى افتراضي.</p></section></SiteShell>; }

export function ExperiencesPage() { return <SiteShell><PageIntro index="07" label="EXPERIENCE" title="الخبرات المهنية" copy="خبراتي العملية والوظائف السابقة" /><section className="section paper-section timeline"><div className="timeline-line" /><article><div className="timeline-date">2023 — 2025</div><div className="timeline-card"><p className="eyebrow dark"><SignalMatrix label="01" /><span>WORK EXPERIENCE</span></p><h2>مهندس موقع</h2><p className="location-line"><MapPin /> اليمن / تعز</p><p>مهندس موقع لرفع وبيان المعلومات التنفيذية المرورية لمراحل التنفي...</p><span className="timeline-badge">الخبرة العملية</span></div></article></section></SiteShell>; }

export function DiscussionPage() { return <SiteShell><PageIntro index="08" label="DISCUSSION" title="المناقشة" copy="مساحة الحوار المرتبطة بالملف المهني." /><section className="section paper-section discussion-note"><MessageCircle /><div><h2>سجل المناقشات قيد التجهيز.</h2><p>تُحافظ هذه النسخة على خصوصية المحادثات ولا تعرض رسائل أو تفاعلات افتراضية. ستصبح مساحة النقاش متاحة هنا عند تجهيز خدمة مخصصة لها.</p></div></section></SiteShell>; }

export function ContactPage() { const [notice, setNotice] = useState(""); const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const subject = String(form.get("subject") || "تواصل من موقع Fahmi Ali"); const body = `الاسم: ${String(form.get("name") || "")}\nالبريد: ${String(form.get("email") || "")}\n\n${String(form.get("message") || "")}`; setNotice("سيُفتح تطبيق البريد لإرسال الرسالة إلى Fahmi Ali."); window.location.href = `mailto:${contact.email}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`; }; return <SiteShell><PageIntro index="09" label="CONTACT" title="اتصل بـ Fahmi" copy="اختر قناة التواصل المناسبة أو اكتب رسالة ليُفتح تطبيق البريد لديك." /><section className="contact-layout"><div className="contact-panel"><p className="eyebrow"><SignalMatrix label="DIRECT" /><span>DIRECT CONTACT</span></p><a href={`tel:${contact.phone}`}><Phone /> {contact.phone}</a><a href={`mailto:${contact.email}`}><Mail /> {contact.email}</a><a href={contact.social.whatsapp} target="_blank" rel="noreferrer"><MessageCircle /> WhatsApp</a><p><MapPin /> {contact.location}</p></div><form className="contact-form" onSubmit={submit}><label>الاسم<input name="name" required /></label><label>البريد الإلكتروني<input name="email" type="email" required /></label><label>الموضوع<input name="subject" required /></label><label>الرسالة<textarea name="message" rows={6} required /></label><button className="button button-primary" type="submit">إرسال عبر البريد <Send /></button>{notice && <p className="form-notice"><CheckCircle2 /> {notice}</p>}</form></section></SiteShell>; }
